### ISSUE TITLE
Sub-regions in CHP due to recombination events

### ISSUE THREAD

**Issue by gaow** [statgenetics/rvnpl#2]
Here is part of an email from a user:

> the output of `rvnpl collapse` looks a bit weird (especially .map and .dat). For example, the gene DEFB129 on chr20. Instead of a unified gene name, I have DEFB129[1], DEFB129[2] , DEFB129[3], etc. This happens to most of genes in the dataset.

My response: as far as I can recall this is our convention for recombination events. When recombinations are detected within a gene it will be broken into two sub-regions. The fact that "This happens to most of genes in the dataset." seems a little worriesome to me. In the past I haven't observed it happen a lot 

Here is what I think should be done:

1. I will create a docker image for SEQLinkage version 1.0.1 (where I haven't seen it happen a lot in my limited test data) to compare with rv-npl see if the results are the same, and why. 
2. @percylinhai could you comment on this issue? You have been analyzing some larger data than I had. Was this what you also see in your analysis for the RV-NPL paper?

**Comment by percylinhai** [comment]
The update on SEQLinkage for RV-NPL treats the recombination in a slightly different way. For RV-NPL, because the calculation is based on allele-sharing which in this case is haplotype-sharing, we need to make sure that the haplotypes that we used for NPL statistics correspond to the same region across different families. Therefore, if there are two families with recombination in the gene region, the region will be divided into 3 sub-regions if the two recombination sites are not the same (see below).
<img width="652" alt="Recombination" src="https://user-images.githubusercontent.com/8493631/77440674-91741200-6db6-11ea-8861-9318759a5d8e.png">

**Comment by gaow** [comment]
Thanks @percylinhai that explains why previously SEQLinkage (version 1.0.1), which generates sub-regions per family not across families, doesn't seem to have that many recomb events. 

I think this has an impact on within family linkage analysis though: say a family has two variants A and B, both causing disease. A is the first variant in the gene, B is the last one. Some cases in the family has A and some has B. If there is recomb between A and B in **another family** then A and B will be separated to two sub-genes for this particular family, and the CHP will be generated on 2 genes. That will weaken the power compared to when you collapse as one gene instead, such that all cases will be coded 1 in genotype, due to having either A or B.

@percylinhai does it make sense?

**Comment by gaow** [comment]
As discussed with @percylinhai offline, we'll add to SEQLinkage an option to swithc between coding per family CHP and cross family CHP for different user scenarios. 

As for the user's questions in particular, we noticed that s/he didn't specify minor allele frequency cutoff when using option `--rvhaplo`. This will include common variants and can increase *observed* number of recomb events in data. **We will also add to rvnpl a check on frequency cutoff when this switch is turned on**.
